import { Oswald, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

import Header from "../ui/Header";
import Footer from "../ui/Footer";

// Oswald font is used for the headings
const OswaldFont = Oswald({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

// Poppins font is used for the main text
const PoppinsFont = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="h-full" lang="uz">
      <body className={`${OswaldFont.style} flex h-full flex-col antialiased`}>
        <Header />
        <main className="grow">{children}</main>
        <Footer />
        <Toaster position="bottom-center" reverseOrder={false} />
      </body>
    </html>
  );
}
